### ISSUE TITLE
Music Commands are not working even thought i'm in a vc and the error i get is You need to be in a vc to play music

### ISSUE THREAD

**Issue by Pickymarker** [Swag1400/Exeter-Selfbot#10]
Music Commands are not working even thought i'm in a vc and the error i get is You need to be in a vc to play music

**Comment by 8uX** [comment]
it's broken plus swag doesnt give a fuck about this selfbot

**Comment by 8uX** [comment]
oh and it's a token logger so change ur password (even tho the webhook is invalid)
