### ISSUE TITLE
This is logger.

### ISSUE THREAD

**Issue by Somebodyop** [Swag1400/Exeter-Selfbot#16]
Yeah, this is the best logger ever and swag1400 is a skid who steals others' self bot and make them logger please don't use this logging shit it will ger you hacked.

**Comment by Glizzster** [comment]
lmao what? really dude? i was just abt to do that and i saw this damnnnnn

**Comment by Somebodyop** [comment]
Yes this is a logger and this guy swag1400 has absolute trash skills he
skids everything, makes it logger, then traps people plus he has trash
coding skills ain't no match for the real owner of this self bot and there
are like 5-6 guys who claim this self bot as thier and all are loggers
except the real one made by the real owner lol
