### ISSUE TITLE
u fucktard u legit left all servers on my alt :bruh:

### ISSUE THREAD

**Issue by Krzxx** [Swag1400/Exeter-Selfbot#20]

**Comment by 82n** [comment]
since like 1 year the webhook is deleted lmfao

**Comment by Krzxx** [comment]
idk then cuz i was using this on my alt it got nuked (might of been a different a different github link tho)

**Comment by caiocinel** [comment]
This is what happens when using closed source projects.

**Comment by RayZ3R0** [comment]
lmfao, i was about to use it.
